routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');

Auth::routes(['register'=>false]);


Route::get('/home', 'HomeController@index')->name('home');

// Part A Answer

Route::get('/question1', 'PartAController@question1')->name('question1');

Route::get('/question2', 'PartAController@question2')->name('question2');

Route::get('/question3', 'PartAController@question3')->name('question3');

Route::get('/question4', 'PartAController@question4')->name('question4');

Route::get('/question5', 'PartAController@question5')->name('question5');

Route::get('/question6', 'PartAController@question6')->name('question6');

// Part B

Route::resource('/users', 'UserController', ['except' => ['show']])->middleware( 'admin');

Route::resource('/listing', 'ListingController', ['except' => ['show']])->middleware('admin');

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Listing extends Model
{
    protected $guarded = [];

    // link user and listing
    public function user()
    {
        return $this->belongsTo(User::class, 'submitter_id', 'id');
    }
}

app/Http/Controllers/API/ListingController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Listing;
use Location\Coordinate;
use Location\Distance\Vincenty;

class ListingController extends Controller
{
    public function getListing($id, $lat, $long)
    {
        $data = []; // declare variable array

        $listings = Listing::whereSubmitterId($id)->get(); // get listing

        if ($listings) { // if listing exist

            foreach ($listings as $listing){

                $coordinate1 = new Coordinate($lat, $long); // from user input
                $coordinate2 = new Coordinate($listing->latitude, $listing->longitude); // from database

                // data to response
                $data[] = ['id' => $listing->id, 'list_name' => $listing->list_name,
                    'distance' => number_format($coordinate1->getDistance($coordinate2, new Vincenty()) / 1000, 3)];

            }

            // return the data in json
            return response()->json(['listing' => $data,
                'status' => ['code' => 200, 'message' => 'Listing successfully retrieved']], 200);

        } else {

            // if user has not listing exist
            return response()->json(['listing' => 'No data for this user',
                'status' => ['code' => 404, 'message' => 'Listing not available']], 404);

        }



    }
}

app/Http/Controllers/ListingController.php
<?php

namespace App\Http\Controllers;

use App\Listing;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class ListingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // list all listing
        return view('listing.index')->with('listings', Listing::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // show form create listing
        return view('listing.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate user input
        Validator::make($request->all(), [
            'list_name' => 'required',
            'address' => 'required',
            'latitude' => 'required',
            'longitude' => 'required'
        ])->validate();

        // store data in listing model
        Listing::create([
            'list_name' => $request->list_name,
            'address' => $request->address,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
            'submitter_id' => Auth::user()->id
        ]);

        // flash message
        session()->flash('success', 'Listing successfully created!');

        // redirect to listing page
        return redirect('/listing');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function edit(Listing $listing)
    {
        // edit listing by ID
        return view('listing.edit')->with('listing', Listing::findOrFail($listing->id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Listing $listing)
    {
        // find listing
        $listing = Listing::findOrFail($listing->id);

        // validate user input
        Validator::make($request->all(), [
            'list_name' => 'required',
            'address' => 'required',
            'latitude' => 'required',
            'longitude' => 'required'
        ])->validate();

        // update listing
        $listing->update([
            'list_name' => $request->list_name,
            'address' => $request->address,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
            'submitter_id' => Auth::user()->id
        ]);

        // flash message
        session()->flash('success', 'Listing successfully updated!');

        // redirect to listing page
        return redirect('/listing');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function destroy(Listing $listing)
    {
        // get listing
        $listing = Listing::findOrFail($listing->id);

        // delete listing
        $listing->delete();

        // flash message
        session()->flash('success', 'Listing successfully deleted!');

        // redirect to listing page
        return redirect('/listing');
    }
}

resources/views/listing/create.blade.php
@extends('layouts.adminlte')
@section('title')
    Create Listing
@endsection
@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0 text-dark">Create Listing</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Fill the details to create listing</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form method="POST" action="{{ route('listing.store') }}">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="list_name">Name</label>

                                    <div class="col-md-6">
                                        <input id="list_name" type="text" class="form-control @error('list_name') is-invalid @enderror" name="list_name" value="{{ old('list_name') }}" placeholder="e.g. KFC" required autocomplete="list_name" autofocus>

                                        @error('list_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="address">Address</label>

                                    <div class="col-md-6">
                                        <textarea id="address" type="text" cols="3" rows="3" class="form-control @error('address') is-invalid @enderror" name="address" >{{ old('address') }}</textarea>

                                        @error('address')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="latitude">Latitude</label>

                                    <div class="col-md-6">
                                        <input id="latitude" type="text" class="form-control @error('latitude') is-invalid @enderror" name="latitude" value="{{ old('latitude') }}" placeholder="e.g. 111.12345" required autocomplete="latitude" autofocus>

                                        @error('latitude')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="longitude">Longitude</label>

                                    <div class="col-md-6">
                                        <input id="longitude" type="text" class="form-control @error('longitude') is-invalid @enderror" name="longitude" value="{{ old('longitude') }}" placeholder="e.g. 123.5124131" required autocomplete="longitude" autofocus>

                                        @error('longitude')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>


                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
        </div>
        </div>
    </section>
@endsection

resources/views/listing/edit.blade.php
@extends('layouts.adminlte')
@section('title')
    Edit Listing
@endsection
@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0 text-dark">Edit Listing</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Fill the details to edit listing</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form method="POST" action="{{ route('listing.update', $listing->id) }}">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="list_name">Name</label>

                                    <div class="col-md-6">
                                        <input id="list_name" type="text" class="form-control @error('list_name') is-invalid @enderror" name="list_name" value="{{ $listing->list_name }}" placeholder="e.g. KFC" required autocomplete="list_name" autofocus>

                                        @error('list_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="address">Address</label>

                                    <div class="col-md-6">
                                        <textarea id="address" type="text" cols="3" rows="3" class="form-control @error('address') is-invalid @enderror" name="address" >{{ $listing->address }}</textarea>

                                        @error('address')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="latitude">Latitude</label>

                                    <div class="col-md-6">
                                        <input id="latitude" type="text" class="form-control @error('latitude') is-invalid @enderror" name="latitude" value="{{ $listing->latitude }}" placeholder="e.g. 111.12345" required autocomplete="latitude" autofocus>

                                        @error('latitude')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="longitude">Longitude</label>

                                    <div class="col-md-6">
                                        <input id="longitude" type="text" class="form-control @error('longitude') is-invalid @enderror" name="longitude" value="{{ $listing->longitude }}" placeholder="e.g. 123.5124131" required autocomplete="longitude" autofocus>

                                        @error('longitude')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>


                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/listing/index.blade.php
@extends('layouts.adminlte')
@section('title')
    Listings
@endsection
@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">

            @if(session()->has('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif

            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0 text-dark">Listings</h1>
                </div><!-- /.col -->
                <div class="col-sm-12 mt-2">
                    <a href="{{ route('listing.create') }}" class="btn btn-primary text-white">Create</a>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">List of listing</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Latitude</th>
                                <th>Longitude</th>
                                <th>Submitter Name</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($listings as $listing)
                                <tr>
                                    <td>{{ $listing->id }}</td>
                                    <td>{{ $listing->list_name }}</td>
                                    <td>{{ $listing->address }}</td>
                                    <td>{{ $listing->latitude  }}</td>
                                    <td>{{ $listing->longitude  }}</td>
                                    <td>{{ $listing->user->name }}</td>
                                    <td class="text-center">

                                        <a href="{{ route('listing.edit', $listing->id) }}" class="btn btn-primary btn-icon" title="Edit Listing">
                                            <div><i class="fa fa-edit"></i></div>
                                        </a>

                                        <button class="btn btn-danger btn-icon" data-id="{{ $listing->id }}"data-toggle="modal" data-target="#modaldemo3">
                                            <div><i class="fa fa-trash"></i></div>
                                        </button>

                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
        </div>
    </section>

    <div id="modaldemo3" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Confirmation</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" id="deleteForm" action="#">
                        <p class="lead">Are you sure you want to delete? </p>
                        <br>
                        @csrf
                        @method('DELETE')
                        <div class="modal-footer justify-content-center">
                            <button type="submit" class="btn btn-danger">Confirm</button>
                            <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection